[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#E10600"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2127"
textColor = "#FAFAFA"
font = "sans serif"
